const wordList = [
    { word: "joy", hint: "A feeling of great pleasure" },
    { word: "love", hint: "Deep affection" },
    { word: "peace", hint: "Freedom from disturbance" },
    { word: "hope", hint: "A feeling of expectation" },
    { word: "kindness", hint: "Being friendly and considerate" },
    { word: "gratitude", hint: "Thankfulness" },
    { word: "happiness", hint: "State of being happy" },
    { word: "inspire", hint: "Fill someone with the urge to do something" },
    { word: "smile", hint: "An expression of pleasure" },
    { word: "dream", hint: "A series of thoughts during sleep" },
    { word: "bravery", hint: "Courageous behavior" },
    { word: "loyal", hint: "Giving or showing firm support" },
    { word: "trust", hint: "Firm belief in reliability" },
    { word: "generous", hint: "Showing a readiness to give more" },
    { word: "friendly", hint: "Kind and pleasant" },
    { word: "patience", hint: "Ability to wait without frustration" },
    { word: "wisdom", hint: "Quality of having experience and knowledge" },
    { word: "respect", hint: "A feeling of deep admiration" },
    { word: "forgive", hint: "Stop feeling angry or resentful" },
    { word: "joyful", hint: "Feeling, expressing, or causing great pleasure" },
    { word: "zeal", hint: "Great energy or enthusiasm" },
    { word: "ambition", hint: "A strong desire to achieve something" },
    { word: "courage", hint: "Ability to do something that frightens" },
    { word: "positivity", hint: "Practice of being or tendency to be positive" },
    { word: "cheerful", hint: "Noticeably happy and optimistic" },
    { word: "content", hint: "In a state of peaceful happiness" },
    { word: "faith", hint: "Complete trust or confidence" },
    { word: "honesty", hint: "Quality of being honest" },
    { word: "compassion", hint: "Sympathetic pity and concern" },
    { word: "admire", hint: "Regard with respect or warm approval" },
    { word: "radiant", hint: "Sending out light; shining or glowing" },
    { word: "uplift", hint: "Raise the level of" },
    { word: "vibrant", hint: "Full of energy and enthusiasm" },
    { word: "bliss", hint: "Perfect happiness" },
    { word: "serene", hint: "Calm, peaceful, and untroubled" },
    { word: "jovial", hint: "Cheerful and friendly" },
    { word: "elated", hint: "Make someone ecstatically happy" },
    { word: "motivate", hint: "Provide with a reason to act" },
    { word: "enthusiastic", hint: "Having or showing intense interest" },
    { word: "lion", hint: "King of the jungle" },
    { word: "eagle", hint: "Bird of prey with excellent vision" },
    { word: "dolphin", hint: "Intelligent marine mammal" },
    { word: "butterfly", hint: "Insect known for its colorful wings" },
    { word: "elephant", hint: "Largest land animal" },
    { word: "giraffe", hint: "Tallest land animal" },
    { word: "penguin", hint: "Flightless bird that swims" },
    { word: "tiger", hint: "Large feline with stripes" },
    { word: "koala", hint: "Tree-dwelling Australian marsupial" },
    { word: "panda", hint: "Black and white bear from China" },
    { word: "flamingo", hint: "Bird known for its pink color and one-legged stance" },
    { word: "kangaroo", hint: "Australian marsupial that hops" },
    { word: "zebra", hint: "African animal with black-and-white stripes" },
    { word: "parrot", hint: "Colorful bird that can mimic speech" },
    { word: "cheetah", hint: "Fastest land animal" },
    { word: "orca", hint: "Marine mammal also known as a killer whale" },
    { word: "peacock", hint: "Bird with a large, colorful tail" },
    { word: "owl", hint: "Bird known for its wisdom" },
    { word: "rabbit", hint: "Small mammal with long ears" },
    { word: "turtle", hint: "Reptile with a hard shell" },
    { word: "swan", hint: "Graceful bird with a long neck" },
    { word: "octopus", hint: "Eight-armed sea creature" },
    { word: "leopard", hint: "Large spotted feline" },
    { word: "rhinoceros", hint: "Large, thick-skinned herbivore with horns" },
    { word: "hippopotamus", hint: "Large semi-aquatic mammal" },
    { word: "gorilla", hint: "Large, powerful primate" },
    { word: "chimpanzee", hint: "Intelligent primate" },
    { word: "whale", hint: "Largest marine mammal" },
    { word: "shark", hint: "Predatory fish known for its teeth" },
    { word: "wolf", hint: "Wild canine known for its pack behavior" },
    { word: "fox", hint: "Cunning wild canine" },
    { word: "deer", hint: "Gentle herbivore with antlers" },
    { word: "squirrel", hint: "Small mammal known for storing nuts" },
    { word: "hedgehog", hint: "Small spiny mammal" },
    { word: "hamster", hint: "Small rodent often kept as a pet" },
    { word: "iguana", hint: "Large herbivorous lizard" },
    { word: "gecko", hint: "Small lizard known for its climbing abilities" },
    { word: "tortoise", hint: "Land-dwelling reptile with a shell" },
    { word: "crane", hint: "Large bird known for its long legs and neck" },
    { word: "albatross", hint: "Large seabird known for its long wingspan" },
    { word: "hummingbird", hint: "Small bird known for its rapid wing beats" },
    { word: "sparrow", hint: "Small, common bird" },
    { word: "falcon", hint: "Bird of prey known for its speed" },
    { word: "beaver", hint: "Diligent rodent known for building dams" },
    { word: "otter", hint: "Playful aquatic mammal" },
    { word: "platypus", hint: "Egg-laying mammal with a duck bill" },
    { word: "sloth", hint: "Slow-moving tree-dwelling mammal" },
    { word: "armadillo", hint: "Mammal with a leathery armor shell" },
    { word: "meerkat", hint: "Small mongoose known for standing upright" },
    { word: "lemur", hint: "Primates known for their large eyes" },
    { word: "badger", hint: "Burrowing nocturnal mammal" },
    { word: "beetle", hint: "Insect with a hard shell" }
];
